config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get "home", to: "pages#home"

  # Session and registration routes
  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations" }

  # User routes
  resources :users, only: [ :index, :edit, :update, :show ] do
    member do
      patch :deactivate
      patch :activate
    end
  end

  # Sale routes
  resources :sales do
    member do
      patch :cancel
    end
    collection do
      get :set_products_amount
      post :set_products_amount
    end
  end


  # Product sale routes
  resources :product_sales

  # Client routes
  resources :clients, only: [ :index, :new, :create, :destroy ]

  # Category and product routes
  resources :products
  resources :categories, only: [ :index, :new, :create, :destroy ]

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/user.rb
class User < ApplicationRecord
  enum :role_int, admin: 0, manager: 1, employee: 2
  before_create :set_joined_at

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, presence: true, uniqueness: true
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP, message: "must be a valid email address" }

  validates :phone, presence: true, format: { with: /\A(\+?\d{1,3}[-.\s]?)?(\(?\d{2,3}\)?[-.\s]?)?(\d{3}[-.\s]?\d{4})\z/, message: "must be a valid phone number" }
  validates :role_int, inclusion: { in: role_ints.keys.map { |role| role.to_s }, message: "%{value} Role invalido." }
  validates :password, presence: true, length: { minimum: 6 }, if: :password_required?

  def deactivate!
    update(is_active: false, password: Devise.friendly_token[0, 6])
  end

  def activate!
    update(is_active: true, password: "new-password")
  end

  def is_admin?
    role_int == "admin"
  end

  def is_manager?
    role_int == "manager"
  end

  def is_employee?
    role_int == "employee"
  end

  private
  def set_joined_at
    self.joined_at = Time.current unless joined_at
  end

  def password_required?
    new_record? || password.present?
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  skip_before_action :require_no_authentication, only: [ :new, :create ]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end


  def create
    @user = User.new(user_params)
    authorize! :create, @user
    if @user.save
      redirect_to users_path, notice: "User created"
    else
      flash.now[:alert] = @user.errors.full_messages.join(", ")
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :phone, :password, :password_confirmation, :role_int)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    authorize! :index, User
    @users = User.where.not(id: current_user.id)
    @current_user = current_user
  end

  def show
    @user = User.find_by(id: params[:id])
    if @user.nil?
        content_not_found
    end
    authorize! :show, @user
  end

  def edit
    @user = User.find(params[:id])
    authorize! :edit, @user
  end

  def update
    @user = User.find(params[:id])
    authorize! :update, @user
    if @user.update(user_params)
      redirect_to root_path, notice: "User updated"
    else
      flash.now[:alert] = @user.errors.full_messages.join(", ")
      render :edit
    end
  end

  def deactivate
    @user = User.find(params[:id])
    authorize! :deactivate, @user
    @user.deactivate!
    redirect_to users_path, notice: "User deactivated"
  end

  def activate
    @user = User.find(params[:id])
    authorize! :activate, @user
    @user.activate!
    redirect_to users_path, notice: "User activated"
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :phone, :password, :password_confirmation, :role_int, :is_active)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container mt-5">
  <h1 class="text-center text-primary mb-4">Edit User</h1>

  <%= form_with model: @user, class: 'needs-validation' do |form| %>
    <div class="row mb-3">
      <div class="col-md-6">
        <%= form.label :username, class: 'form-label' %>
        <%= form.text_field :username, class: 'form-control', placeholder: 'e.g., johndoe' %>
      </div>
      <div class="col-md-6">
        <%= form.label :email, class: 'form-label' %>
        <%= form.email_field :email, class: 'form-control', placeholder: 'e.g., johndoe@example.com' %>
      </div>
    </div>

    <div class="row mb-3">
      <div class="col-md-6">
        <%= form.label :phone, class: 'form-label' %>
        <%= form.telephone_field :phone, class: 'form-control', placeholder: 'e.g., (123) 456-7890' %>
      </div>
    </div>

    <div class="row mb-3">
      <div class="col-md-6">
        <%= form.label :password, "New password", class: 'form-label' %>
        <% if @minimum_password_length %>
          <em class="text-muted d-block mb-2">(<%= @minimum_password_length %> characters minimum)</em>
        <% end %>
        <%= form.password_field :password, class: 'form-control', placeholder: 'Enter new password', autocomplete: "new-password" %>
      </div>

      <div class="col-md-6">
        <%= form.label :password_confirmation, "Confirm new password", class: 'form-label' %>
        <%= form.password_field :password_confirmation, class: 'form-control', placeholder: 'Re-enter new password', autocomplete: "new-password" %>
      </div>
    </div>

    <div class="d-grid gap-2">
      <%= form.submit 'Save Changes', class: 'btn btn-primary btn-lg' %>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<div class="container mt-4">
  <h1 class="text-center text-primary mb-4">Users List</h1>

  <% if can? :create, User %>
  <div class="text-end mb-3">
    <%= link_to "Register new user",  new_user_registration_path, class: 'btn btn-primary' %><br />
  </div>
  <% end %>

  <p class="mb-4">Users count: <%= @users.count %></p>

  <% if @users.count > 0 %>
    <table class="table table-striped table-bordered">
      <thead class="table-dark">
        <tr>
          <th>Email</th>
          <th>Username</th>
          <th>Phone</th>
          <th>Role</th>
          <th>Active</th>
          <th>Actions</th>
        </tr>
      </thead>

      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= link_to user.email, user_path(user) %></td>
            <td><%= user.username %></td>
            <td><%= user.phone %></td>
            <td><%= user.role_int %></td>
            <td>
                <% if user.is_active %>
                    <span>Yes</span>
                <% else %>
                    <span>No</span>
                <% end %>
            </td>
            <td>
            <div class="d-flex">

              <% if user.is_active %>
                <% if can? :deactivate, user %>
                  <%= button_to 'Deactivate', deactivate_user_path(user), method: :patch, class: 'btn btn-danger btn-sm me-2' %>
                <% end %>
              <% else %>

                <% if can? :activate, user %>
                  <%= button_to 'Activate', activate_user_path(user), method: :patch, class: 'btn btn-success btn-sm me-2' %>
                <% end %>
              <% end %>

              <% if can? :update, user %>
                <%= link_to 'Edit', edit_user_path(user), class: 'btn btn-primary btn-sm' %>
              <% end %>

            </div>
            </td>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <p class="text-center text-danger">There are no users to show</p>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="container mt-4">
  <h1 class="text-center text-primary mb-4">User: <%= @user.username %></h1>

  <div class="row">
    <div class="col-md-6 mb-3">
      <strong>Email:</strong>
      <span><%= @user.email %></span>
    </div>

    <div class="col-md-6 mb-3">
      <strong>Username:</strong>
      <span><%= @user.username %></span>
    </div>

    <div class="col-md-6 mb-3">
      <strong>Phone:</strong>
      <span><%= @user.phone %></span>
    </div>

    <div class="col-md-6 mb-3">
      <strong>Role:</strong>
      <span><%= @user.role_int %></span>
    </div>

    <div class="col-md-6 mb-3">
      <strong>Active:</strong>
      <span>
        <% if @user.is_active %>
          <span>Yes</span>
        <% else %>
          <span>No</span>
        <% end %>
      </span>
    </div>

  </div>

  <% if can? :edit, @user %>
    <%= link_to 'Edit', edit_user_path(@user), class: 'btn btn-primary btn-sm' %>
  <% end %>
</div>