config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get "home", to: "pages#home"

  # Session and registration routes
  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations" }

  # User routes
  resources :users, only: [ :index, :edit, :update, :show ] do
    member do
      patch :deactivate
      patch :activate
    end
  end

  # Sale routes
  resources :sales do
    member do
      patch :cancel
    end
    collection do
      get :set_products_amount
      post :set_products_amount
    end
  end


  # Product sale routes
  resources :product_sales

  # Client routes
  resources :clients, only: [ :index, :new, :create, :destroy ]

  # Category and product routes
  resources :products
  resources :categories, only: [ :index, :new, :create, :destroy ]

  get "up" => "rails/health#show", as: :rails_health_check
end

app/views/shared/_flash.html.erb
<% if notice %>
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <strong>Success!</strong> <%= notice %>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <strong>Warning!</strong> <%= alert %>
  </div>
<% end %>

app/views/shared/_header.html.erb
<header class="container mt-4">
  <div class="text-center mb-3">
    <h1 class="fw-bold text-primary">Avivas Sportswear Store</h1>
  </div>
  
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <ul class="navbar-nav">

        <li class="nav-item">
          <%= link_to 'Home', root_path, class: 'nav-link' %>
        </li>

        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="dropdownMenuButton" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Products
            </a>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <% if can? :read, Product %>
                <li class="nav-item">
                  <a class="dropdown-item" href=<%=products_path%>>Products list</a>    
                </li>
              <% end %>

              <% if can? :read, Category %>
                <li class="nav-item">
                  <a class="dropdown-item" href=<%=categories_path%>>Categories</a>    
                </li>
              <% end %>
            </ul>
          </li>
        <% end %>
        
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="dropdownMenuButton" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Sales
            </a>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <% if can? :read, Sale %>
                <li class="nav-item">
                  <a class="dropdown-item" href=<%=sales_path%>>Sales list</a>    
                </li>
              <% end %>

              <% if can? :read, Client %>
                <li class="nav-item">
                  <a class="dropdown-item" href=<%=clients_path%>>Clients</a>    
                </li>
              <% end %>
            </ul>
          </li>
        <% end %>

        <% if can? :read, User %>
        <li class="nav-item">
          <%= link_to 'Users', users_path, class: 'nav-link' %>
        </li>
        <% end %>
        
      </ul>

      <% if user_signed_in? %>
        <ul class="navbar-nav ms-auto">
          <li class="nav-item">
            <%= link_to 'Profile', user_path(current_user), class: 'btn btn-info m-2' %>
          </li>
          <li class="nav-item">
            <%= button_to 'Log out', destroy_user_session_path, method: :delete, class: 'btn btn-danger m-2' %>
          </li>
        </ul>
      <% else %>
        <ul class="navbar-nav ms-auto">
          <li class="nav-item">
            <%= link_to 'Log in', new_user_session_path, class: 'btn btn-primary' %>
          </li>
        </ul>
      <% end %>

    </div>
  </nav>

  <hr>
</header>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>