config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get "home", to: "pages#home"

  # Session and registration routes
  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations" }

  # User routes
  resources :users, only: [ :index, :edit, :update, :show ] do
    member do
      patch :deactivate
      patch :activate
    end
  end

  # Sale routes
  resources :sales do
    member do
      patch :cancel
    end
    collection do
      get :set_products_amount
      post :set_products_amount
    end
  end


  # Product sale routes
  resources :product_sales

  # Client routes
  resources :clients, only: [ :index, :new, :create, :destroy ]

  # Category and product routes
  resources :products
  resources :categories, only: [ :index, :new, :create, :destroy ]

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/sale.rb
class Sale < ApplicationRecord
  before_create :set_date_and_time
  before_create :check_stock

  belongs_to :user
  belongs_to :client
  has_many :product_sale, dependent: :destroy
  has_many :product, through: :product_sale

  accepts_nested_attributes_for :product_sale, allow_destroy: true

  validates :user_id, presence: true
  validates :client_id, presence: true

  private

  def check_stock
    product_sale.each do |ps|
      product = ps.product
      if product.stock < ps.quantity
        errors.add(:base, "The product #{product.name} does not have enough stock")
        throw :abort
      end
    end
  end

  def set_date_and_time
    self.date_time = DateTime.now
  end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  def index
    @sales = Sale.all
    authorize! :read, Sale
  end

  def new
    @product_amount = params[:products_amount].to_i

    if @product_amount <= 0 || @product_amount.nil?
      flash.now[:alert] = "Please select the number of products you want to include into the sale"
      render :set_products_amount
    else
      @sale = Sale.new
      authorize! :create, Sale
      @product_amount.times { @sale.product_sale.build }
    end
  end

  # This method is used to create a new sale in the following way:
  # 1. The sale will be created
  # 2. The stock of the products included in the sale will be updated
  # If any of the steps fails, the transaction will be rolled back
  def create
    authorize! :create, Sale
    ActiveRecord::Base.transaction do
      @sale = Sale.new(sale_params)

      if @sale.invalid?
        flash.now[:alert] = @sale.errors.full_messages.join(" | ")
        render :new
        return
      end

      total = @sale.product_sale.map { |ps| ps.product.price * ps.quantity }.sum
      @sale.total_price = total

      if @sale.save

        @sale.product_sale.each do |ps|
          product = ps.product
          product.update!(stock: product.stock - ps.quantity)
        end
        redirect_to sales_path, notice: "Sale saved correctly"
        return
      else
        raise ActiveRecord::Rollback
      end
    end

    flash.now[:alert] = "There was an error saving the sale: #{@sale.errors.full_messages.join(" | ")}"
    render :new
  end

  # This method is used to set the number of products that will be included into the sale
  def set_products_amount
    if request.get?
      @products_amount = 1

    elsif request.post?
      @products_amount = params[:products_amount].to_i

      if @products_amount <= 0
        flash.now[:alert] = "Please select a number greater than 0"
        render :set_products_amount
      else
        redirect_to new_sale_path(products_amount: @products_amount)
      end
    end
  end

  def cancel
    authorize! :update, Sale
    @sale = Sale.find(params[:id])
    if @sale.active == false
      return redirect_to sales_path, notice: "The sale is already canceled"
    end
    ActiveRecord::Base.transaction do
      @sale.update!(active: false)
      @sale.product_sale.each do |ps|
        product = ps.product
        product.update!(stock: product.stock + ps.quantity)
      end
    end
    redirect_to sales_path, notice: "Sale canceled and stock reverted"
  end

  private
  def sale_params
    params.require(:sale).permit(:user_id, :client_id, product_sale_attributes: [  :product_id, :quantity, :_destroy ])
  end
end

app/views/sales/index.html.erb
<div class="container mt-4">
  <h1 class="text-center text-primary mb-4">Sales List</h1>

  <!-- Falta validaciones de CanCanCan -->

<% if can? :create, Sale %>
    <div class="text-end mb-3">
    <%= link_to 'Add new sale', set_products_amount_sales_path, class: 'btn btn-success' %>
    </div>
<% end %>

  <p class="mb-4">Sales count: <%= @sales.count %></p>

  <% if @sales.count > 0 %>
    <table class="table table-striped table-bordered">
      <thead class="table-dark">
        <tr>
          <th>Date & Time</th>
          <th>Products</th>
          <th>Total</th>
          <th>Employee</th>
          <th>Client</th>
          <th>Actions</th>
        </tr>
      </thead>

      <tbody>
        <% @sales.each do |sale| %>
          <tr class="<%= 'table-secondary' unless sale.active %>">
            <td><%= sale.created_at.strftime("%Y-%m-%d %H:%M:%S") %></td>
            <td>
              <% sale.product_sale.each do |ps| %>
                <p>
                  <%= ps.product.name %> - Quantity: <%= ps.quantity %> - Price: <%= number_to_currency(ps.product.price) %>
                </p>
              <% end %>
            </td>
            <td><%= number_to_currency(sale.total_price) %></td>
            <td><%= sale.user.username %></td>
            <td><%= sale.client.name %></td>
            <td>
              <div class="d-flex">
                <% if can? :edit, Sale %>
                    <% if sale.active %>
                        <%= button_to 'Cancel', cancel_sale_path(sale), method: :patch, class: 'btn btn-danger btn-sm' %>
                    <% end %>
                <% end %>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <p class="text-center text-danger">There are no sales to show</p>
  <% end %>
</div>

app/views/sales/new.html.erb
<h1 class="text-center my-4">Add New Sale</h1>

<%= form_with model: @sale, local: true, class: "container" do |form| %>

  <!-- Product's List Section -->
  <div class="card mb-4">
    <div class="card-header">
      <h5>Product's List</h5>
    </div>

    <div id='products-container' class="card-body">

      <%= form.fields_for :product_sale do |item| %>

        <div>

          <!-- Product Selection -->
          <div>
            <%= item.label :product_id, "Product", class: "form-label" %>
            <%= item.collection_select :product_id, Product.all, :id, :name, { include_blank: true }, class: "input-field" %>
          </div>

          <!-- Quantity -->
          <div>
            <%= item.label :quantity, "Quantity", class: "form-label" %>
            <%= item.number_field :quantity, step: 1, min: 1, class: "input-field" %>
          </div>
        </div>

        <!-- Checkbox to delete product
        <div class="form-check mb-3">
          <%= item.check_box :_destroy, class: "form-check-input" %>
          <%= item.label :_destroy, "Remove Product", class: "form-check-label" %>
        </div>
        -->


      <% end %>
    </div>
    
  </div>

  <!-- Employee Section -->
  <div class="card mb-4">

    <div class="card-header">
      <h5>Employee</h5>
    </div>
    
    <div class="card-body">
      <div class="mb-3">
        <%= form.label :user_id, "Employee", class: "form-label" %>
        <%= form.collection_select :user_id, User.all, :id, :username, { include_blank: true }, class: "form-select" %>
      </div>
    </div>

  </div>

  <!-- Client Section -->
  <div class="card mb-4">

    <div class="card-header">
      <h5>Client</h5>
    </div>

    <div class="card-body">

      <div class="mb-3">
        <%= form.label :client_id, "Client", class: "form-label" %>
        <%= form.collection_select :client_id, Client.all, :id, :name, { include_blank: true }, { class: "form-select" , id: "" } %>
      </div>

      <%=link_to "Add new client" , new_client_path , class:"btn btn-primary mb-3" %>
    </div>

  </div>

  <!-- Submit Button -->
  <div class="text-center">
    <%= form.submit "Save Sale", class: "btn btn-success" %>
    <button type="button" class="btn btn-secondary" onclick="window.location.href='<%= sales_path %>'">Cancel</button>
  </div>

<% end %>

app/views/sales/set_products_amount.html.erb
<p> Please, enter the number of products you want to include into the sale </p>
<%= form_with url: '/sales/set_products_amount', method: :post do |form| %>
  <div class="mb-3">
    <%= form.number_field :products_amount, min: 1, class: "form-control", value: @product_count %>
  </div>

  <%= form.submit "Next", class: "btn btn-primary" %>
<% end %>